# Generated by Django 3.1.3 on 2026-05-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_auto_20260422_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='productos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
